package com.example.Student_Library_Management_System.Services;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    StudentRepository studentRepository;
    public String createStudent(Student student){
        //Student from postman is already a basic attributes set

        //card should be autogenerated when create student is called
        Card card = new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student);

        student.setCard(card);

        //If there was unidirectional mapping, we had to save both parent and child individually

        //Since we are using bidirectional mapping, child will automatically be saved

        studentRepository.save(student);
        //by cascading effect child will automatically be saved

        return "Student and Card added";
    }
}
